version: '3'
services:
  db:
    image: eventstore/eventstore
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
        EVENTSTORE_RUN_PROJECTIONS: All
        EVENTSTORE_START_STANDARD_PROJECTIONS: All
    ports:
      - "2113:2113"
  driver:
    build:
        context: .
        dockerfile: Dockerfile
    environment:
        NO_PROXY: db
        no_proxy: db
    stdin_open: true
    tty: true
    volumes:
      - .:/code
    depends_on:
      - db
